# Generated by Django 5.0.7 on 2024-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('song_code', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='singers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=10)),
                ('singer_address', models.CharField(max_length=50)),
                ('singer_Id', models.ManyToManyField(to='music.songs')),
            ],
        ),
    ]
