# Generated by Django 5.0.7 on 2024-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singers',
            name='singer_Id',
            field=models.ManyToManyField(related_name='uniq', to='music.songs'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_code',
            field=models.IntegerField(),
        ),
    ]
