# Generated by Django 4.2.14 on 2024-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_remove_airport_duration_flight_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('flights', models.ManyToManyField(related_name='passengers', to='airline.flight')),
            ],
        ),
    ]
